spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:TradingCrypto
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
